;; Auto-generated by problem_generator — DO NOT EDIT BY HAND
;; Generated at: {{ generated_at }}

(define (problem ev-prep-{{ ts }})
  (:domain ev-cabin-prep)

  (:init
    ;; Boolean state — only positive literals (closed-world assumption: unlisted = false)
    {% if charging %}(charging){% endif %}
    {% if hvac_on %}(hvac-on){% endif %}
    {% if seat_warmer_on %}(seat-warmer-on){% endif %}
    {% if lights_on %}(lights-on){% endif %}
    {% if route_loaded %}(route-loaded){% endif %}
    {% if charger_available %}(charger-available){% endif %}

    ;; Numeric fluents
    (= (battery-soc) {{ battery_soc | round(2) }})
    (= (target-soc) {{ target_soc | round(2) }})
    (= (cabin-temp) {{ cabin_temp | round(2) }})
    (= (target-cabin-temp) {{ target_cabin_temp | round(2) }})
    (= (outside-temp) {{ outside_temp | round(2) }})
    (= (time-remaining) {{ time_remaining | round(2) }})
    (= (total-power-draw) {{ total_power_draw | round(2) }})
    (= (max-power) {{ max_power | round(2) }})
    (= (charge-rate-pct-per-min) {{ charge_rate_pct_per_min | round(4) }})
    (= (hvac-power-w) {{ hvac_power_w | round(2) }})
    (= (seat-warmer-power-w) {{ seat_warmer_power_w | round(2) }})
    (= (charger-power-w) {{ charger_power_w | round(2) }})
    (= (cooling-coeff) {{ cooling_coeff | round(4) }})
    (= (heater-delta-per-min) {{ heater_delta_per_min | round(4) }})
  )

  (:goal
    (and
      (>= (battery-soc) (target-soc))
      (>= (cabin-temp) (target-cabin-temp))
      (route-loaded)
    )
  )

  (:metric minimize (total-time))
)
